//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Dgfb
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Организация.
    /// </summary>
    // *** Start programmer edit section *** (Организация CustomAttributes)

    // *** End programmer edit section *** (Организация CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОрганизацияE", new string[] {
            "Наименование as \'Наименование\'",
            "ЮрАдерс as \'Юр адерс\'",
            "Телефон as \'Телефон\'",
            "Почта as \'Почта\'"})]
    [View("ОрганизацияL", new string[] {
            "Наименование as \'Наименование\'",
            "ЮрАдерс as \'Юр адерс\'",
            "Телефон as \'Телефон\'",
            "Почта as \'Почта\'"})]
    public class Организация : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private string fЮрАдерс;
        
        private int fТелефон;
        
        private string fПочта;
        
        // *** Start programmer edit section *** (Организация CustomMembers)

        // *** End programmer edit section *** (Организация CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Организация.Наименование CustomAttributes)

        // *** End programmer edit section *** (Организация.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Организация.Наименование Get start)

                // *** End programmer edit section *** (Организация.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Организация.Наименование Get end)

                // *** End programmer edit section *** (Организация.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.Наименование Set start)

                // *** End programmer edit section *** (Организация.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Организация.Наименование Set end)

                // *** End programmer edit section *** (Организация.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Почта.
        /// </summary>
        // *** Start programmer edit section *** (Организация.Почта CustomAttributes)

        // *** End programmer edit section *** (Организация.Почта CustomAttributes)
        [StrLen(255)]
        public virtual string Почта
        {
            get
            {
                // *** Start programmer edit section *** (Организация.Почта Get start)

                // *** End programmer edit section *** (Организация.Почта Get start)
                string result = this.fПочта;
                // *** Start programmer edit section *** (Организация.Почта Get end)

                // *** End programmer edit section *** (Организация.Почта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.Почта Set start)

                // *** End programmer edit section *** (Организация.Почта Set start)
                this.fПочта = value;
                // *** Start programmer edit section *** (Организация.Почта Set end)

                // *** End programmer edit section *** (Организация.Почта Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (Организация.Телефон CustomAttributes)

        // *** End programmer edit section *** (Организация.Телефон CustomAttributes)
        public virtual int Телефон
        {
            get
            {
                // *** Start programmer edit section *** (Организация.Телефон Get start)

                // *** End programmer edit section *** (Организация.Телефон Get start)
                int result = this.fТелефон;
                // *** Start programmer edit section *** (Организация.Телефон Get end)

                // *** End programmer edit section *** (Организация.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.Телефон Set start)

                // *** End programmer edit section *** (Организация.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (Организация.Телефон Set end)

                // *** End programmer edit section *** (Организация.Телефон Set end)
            }
        }
        
        /// <summary>
        /// ЮрАдерс.
        /// </summary>
        // *** Start programmer edit section *** (Организация.ЮрАдерс CustomAttributes)

        // *** End programmer edit section *** (Организация.ЮрАдерс CustomAttributes)
        [StrLen(255)]
        public virtual string ЮрАдерс
        {
            get
            {
                // *** Start programmer edit section *** (Организация.ЮрАдерс Get start)

                // *** End programmer edit section *** (Организация.ЮрАдерс Get start)
                string result = this.fЮрАдерс;
                // *** Start programmer edit section *** (Организация.ЮрАдерс Get end)

                // *** End programmer edit section *** (Организация.ЮрАдерс Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.ЮрАдерс Set start)

                // *** End programmer edit section *** (Организация.ЮрАдерс Set start)
                this.fЮрАдерс = value;
                // *** Start programmer edit section *** (Организация.ЮрАдерс Set end)

                // *** End programmer edit section *** (Организация.ЮрАдерс Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОрганизацияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОрганизацияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОрганизацияE", typeof(IIS.Dgfb.Организация));
                }
            }
            
            /// <summary>
            /// "ОрганизацияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОрганизацияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОрганизацияL", typeof(IIS.Dgfb.Организация));
                }
            }
        }
    }
}
