//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Dgfb
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Путевой лист.
    /// </summary>
    // *** Start programmer edit section *** (ПутевойЛист CustomAttributes)

    // *** End programmer edit section *** (ПутевойЛист CustomAttributes)
    [AutoAltered()]
    [Caption("Путевой лист")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПутевойЛистE", new string[] {
            "Номер as \'Номер\'",
            "ВыдатьТоплива as \'Выдать топлива\'",
            "ДатаВремя as \'Дата время\'",
            "ПунктНазнач as \'Пункт назнач\'",
            "ПунктОтправ as \'Пункт отправ\'",
            "Расстояние as \'Расстояние\'",
            "МаркаГСМ as \'Марка ГСМ\'",
            "ОстатокГСМ as \'Остаток ГСМ\'",
            "Допущен as \'Допущен\'",
            "Персонал as \'Персонал\'",
            "Персонал.ФИО as \'ФИО\'",
            "ТранспСр as \'Трансп ср\'",
            "ТранспСр.Марка as \'Марка\'"}, Hidden=new string[] {
            "Персонал.ФИО",
            "ТранспСр.Марка"})]
    [MasterViewDefineAttribute("ПутевойЛистE", "Персонал", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ПутевойЛистE", "ТранспСр", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Марка")]
    [View("ПутевойЛистL", new string[] {
            "Номер as \'Номер\'",
            "ВыдатьТоплива as \'Выдать топлива\'",
            "ДатаВремя as \'Дата время\'",
            "ПунктНазнач as \'Пункт назнач\'",
            "ПунктОтправ as \'Пункт отправ\'",
            "Расстояние as \'Расстояние\'",
            "МаркаГСМ as \'Марка ГСМ\'",
            "ОстатокГСМ as \'Остаток ГСМ\'",
            "Допущен as \'Допущен\'",
            "Персонал.ФИО as \'ФИО\'",
            "ТранспСр.Марка as \'Марка\'"})]
    public class ПутевойЛист : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private int fВыдатьТоплива;
        
        private System.DateTime fДатаВремя;
        
        private string fПунктНазнач;
        
        private string fПунктОтправ;
        
        private double fРасстояние;
        
        private string fМаркаГСМ;
        
        private double fОстатокГСМ;
        
        private bool fДопущен;
        
        private IIS.Dgfb.Персонал fПерсонал;
        
        private IIS.Dgfb.ТранспСр fТранспСр;
        
        // *** Start programmer edit section *** (ПутевойЛист CustomMembers)

        // *** End programmer edit section *** (ПутевойЛист CustomMembers)

        
        /// <summary>
        /// ВыдатьТоплива.
        /// </summary>
        // *** Start programmer edit section *** (ПутевойЛист.ВыдатьТоплива CustomAttributes)

        // *** End programmer edit section *** (ПутевойЛист.ВыдатьТоплива CustomAttributes)
        public virtual int ВыдатьТоплива
        {
            get
            {
                // *** Start programmer edit section *** (ПутевойЛист.ВыдатьТоплива Get start)

                // *** End programmer edit section *** (ПутевойЛист.ВыдатьТоплива Get start)
                int result = this.fВыдатьТоплива;
                // *** Start programmer edit section *** (ПутевойЛист.ВыдатьТоплива Get end)

                // *** End programmer edit section *** (ПутевойЛист.ВыдатьТоплива Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПутевойЛист.ВыдатьТоплива Set start)

                // *** End programmer edit section *** (ПутевойЛист.ВыдатьТоплива Set start)
                this.fВыдатьТоплива = value;
                // *** Start programmer edit section *** (ПутевойЛист.ВыдатьТоплива Set end)

                // *** End programmer edit section *** (ПутевойЛист.ВыдатьТоплива Set end)
            }
        }
        
        /// <summary>
        /// ДатаВремя.
        /// </summary>
        // *** Start programmer edit section *** (ПутевойЛист.ДатаВремя CustomAttributes)

        // *** End programmer edit section *** (ПутевойЛист.ДатаВремя CustomAttributes)
        public virtual System.DateTime ДатаВремя
        {
            get
            {
                // *** Start programmer edit section *** (ПутевойЛист.ДатаВремя Get start)

                // *** End programmer edit section *** (ПутевойЛист.ДатаВремя Get start)
                System.DateTime result = this.fДатаВремя;
                // *** Start programmer edit section *** (ПутевойЛист.ДатаВремя Get end)

                // *** End programmer edit section *** (ПутевойЛист.ДатаВремя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПутевойЛист.ДатаВремя Set start)

                // *** End programmer edit section *** (ПутевойЛист.ДатаВремя Set start)
                this.fДатаВремя = value;
                // *** Start programmer edit section *** (ПутевойЛист.ДатаВремя Set end)

                // *** End programmer edit section *** (ПутевойЛист.ДатаВремя Set end)
            }
        }
        
        /// <summary>
        /// Допущен.
        /// </summary>
        // *** Start programmer edit section *** (ПутевойЛист.Допущен CustomAttributes)

        // *** End programmer edit section *** (ПутевойЛист.Допущен CustomAttributes)
        public virtual bool Допущен
        {
            get
            {
                // *** Start programmer edit section *** (ПутевойЛист.Допущен Get start)

                // *** End programmer edit section *** (ПутевойЛист.Допущен Get start)
                bool result = this.fДопущен;
                // *** Start programmer edit section *** (ПутевойЛист.Допущен Get end)

                // *** End programmer edit section *** (ПутевойЛист.Допущен Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПутевойЛист.Допущен Set start)

                // *** End programmer edit section *** (ПутевойЛист.Допущен Set start)
                this.fДопущен = value;
                // *** Start programmer edit section *** (ПутевойЛист.Допущен Set end)

                // *** End programmer edit section *** (ПутевойЛист.Допущен Set end)
            }
        }
        
        /// <summary>
        /// МаркаГСМ.
        /// </summary>
        // *** Start programmer edit section *** (ПутевойЛист.МаркаГСМ CustomAttributes)

        // *** End programmer edit section *** (ПутевойЛист.МаркаГСМ CustomAttributes)
        [StrLen(255)]
        public virtual string МаркаГСМ
        {
            get
            {
                // *** Start programmer edit section *** (ПутевойЛист.МаркаГСМ Get start)

                // *** End programmer edit section *** (ПутевойЛист.МаркаГСМ Get start)
                string result = this.fМаркаГСМ;
                // *** Start programmer edit section *** (ПутевойЛист.МаркаГСМ Get end)

                // *** End programmer edit section *** (ПутевойЛист.МаркаГСМ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПутевойЛист.МаркаГСМ Set start)

                // *** End programmer edit section *** (ПутевойЛист.МаркаГСМ Set start)
                this.fМаркаГСМ = value;
                // *** Start programmer edit section *** (ПутевойЛист.МаркаГСМ Set end)

                // *** End programmer edit section *** (ПутевойЛист.МаркаГСМ Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ПутевойЛист.Номер CustomAttributes)

        // *** End programmer edit section *** (ПутевойЛист.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ПутевойЛист.Номер Get start)

                // *** End programmer edit section *** (ПутевойЛист.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ПутевойЛист.Номер Get end)

                // *** End programmer edit section *** (ПутевойЛист.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПутевойЛист.Номер Set start)

                // *** End programmer edit section *** (ПутевойЛист.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ПутевойЛист.Номер Set end)

                // *** End programmer edit section *** (ПутевойЛист.Номер Set end)
            }
        }
        
        /// <summary>
        /// ОстатокГСМ.
        /// </summary>
        // *** Start programmer edit section *** (ПутевойЛист.ОстатокГСМ CustomAttributes)

        // *** End programmer edit section *** (ПутевойЛист.ОстатокГСМ CustomAttributes)
        public virtual double ОстатокГСМ
        {
            get
            {
                // *** Start programmer edit section *** (ПутевойЛист.ОстатокГСМ Get start)

                // *** End programmer edit section *** (ПутевойЛист.ОстатокГСМ Get start)
                double result = this.fОстатокГСМ;
                // *** Start programmer edit section *** (ПутевойЛист.ОстатокГСМ Get end)

                // *** End programmer edit section *** (ПутевойЛист.ОстатокГСМ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПутевойЛист.ОстатокГСМ Set start)

                // *** End programmer edit section *** (ПутевойЛист.ОстатокГСМ Set start)
                this.fОстатокГСМ = value;
                // *** Start programmer edit section *** (ПутевойЛист.ОстатокГСМ Set end)

                // *** End programmer edit section *** (ПутевойЛист.ОстатокГСМ Set end)
            }
        }
        
        /// <summary>
        /// ПунктНазнач.
        /// </summary>
        // *** Start programmer edit section *** (ПутевойЛист.ПунктНазнач CustomAttributes)

        // *** End programmer edit section *** (ПутевойЛист.ПунктНазнач CustomAttributes)
        [StrLen(255)]
        public virtual string ПунктНазнач
        {
            get
            {
                // *** Start programmer edit section *** (ПутевойЛист.ПунктНазнач Get start)

                // *** End programmer edit section *** (ПутевойЛист.ПунктНазнач Get start)
                string result = this.fПунктНазнач;
                // *** Start programmer edit section *** (ПутевойЛист.ПунктНазнач Get end)

                // *** End programmer edit section *** (ПутевойЛист.ПунктНазнач Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПутевойЛист.ПунктНазнач Set start)

                // *** End programmer edit section *** (ПутевойЛист.ПунктНазнач Set start)
                this.fПунктНазнач = value;
                // *** Start programmer edit section *** (ПутевойЛист.ПунктНазнач Set end)

                // *** End programmer edit section *** (ПутевойЛист.ПунктНазнач Set end)
            }
        }
        
        /// <summary>
        /// ПунктОтправ.
        /// </summary>
        // *** Start programmer edit section *** (ПутевойЛист.ПунктОтправ CustomAttributes)

        // *** End programmer edit section *** (ПутевойЛист.ПунктОтправ CustomAttributes)
        [StrLen(255)]
        public virtual string ПунктОтправ
        {
            get
            {
                // *** Start programmer edit section *** (ПутевойЛист.ПунктОтправ Get start)

                // *** End programmer edit section *** (ПутевойЛист.ПунктОтправ Get start)
                string result = this.fПунктОтправ;
                // *** Start programmer edit section *** (ПутевойЛист.ПунктОтправ Get end)

                // *** End programmer edit section *** (ПутевойЛист.ПунктОтправ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПутевойЛист.ПунктОтправ Set start)

                // *** End programmer edit section *** (ПутевойЛист.ПунктОтправ Set start)
                this.fПунктОтправ = value;
                // *** Start programmer edit section *** (ПутевойЛист.ПунктОтправ Set end)

                // *** End programmer edit section *** (ПутевойЛист.ПунктОтправ Set end)
            }
        }
        
        /// <summary>
        /// Расстояние.
        /// </summary>
        // *** Start programmer edit section *** (ПутевойЛист.Расстояние CustomAttributes)

        // *** End programmer edit section *** (ПутевойЛист.Расстояние CustomAttributes)
        public virtual double Расстояние
        {
            get
            {
                // *** Start programmer edit section *** (ПутевойЛист.Расстояние Get start)

                // *** End programmer edit section *** (ПутевойЛист.Расстояние Get start)
                double result = this.fРасстояние;
                // *** Start programmer edit section *** (ПутевойЛист.Расстояние Get end)

                // *** End programmer edit section *** (ПутевойЛист.Расстояние Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПутевойЛист.Расстояние Set start)

                // *** End programmer edit section *** (ПутевойЛист.Расстояние Set start)
                this.fРасстояние = value;
                // *** Start programmer edit section *** (ПутевойЛист.Расстояние Set end)

                // *** End programmer edit section *** (ПутевойЛист.Расстояние Set end)
            }
        }
        
        /// <summary>
        /// Путевой лист.
        /// </summary>
        // *** Start programmer edit section *** (ПутевойЛист.Персонал CustomAttributes)

        // *** End programmer edit section *** (ПутевойЛист.Персонал CustomAttributes)
        [PropertyStorage(new string[] {
                "Персонал"})]
        [NotNull()]
        public virtual IIS.Dgfb.Персонал Персонал
        {
            get
            {
                // *** Start programmer edit section *** (ПутевойЛист.Персонал Get start)

                // *** End programmer edit section *** (ПутевойЛист.Персонал Get start)
                IIS.Dgfb.Персонал result = this.fПерсонал;
                // *** Start programmer edit section *** (ПутевойЛист.Персонал Get end)

                // *** End programmer edit section *** (ПутевойЛист.Персонал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПутевойЛист.Персонал Set start)

                // *** End programmer edit section *** (ПутевойЛист.Персонал Set start)
                this.fПерсонал = value;
                // *** Start programmer edit section *** (ПутевойЛист.Персонал Set end)

                // *** End programmer edit section *** (ПутевойЛист.Персонал Set end)
            }
        }
        
        /// <summary>
        /// Путевой лист.
        /// </summary>
        // *** Start programmer edit section *** (ПутевойЛист.ТранспСр CustomAttributes)

        // *** End programmer edit section *** (ПутевойЛист.ТранспСр CustomAttributes)
        [PropertyStorage(new string[] {
                "ТранспСр"})]
        [NotNull()]
        public virtual IIS.Dgfb.ТранспСр ТранспСр
        {
            get
            {
                // *** Start programmer edit section *** (ПутевойЛист.ТранспСр Get start)

                // *** End programmer edit section *** (ПутевойЛист.ТранспСр Get start)
                IIS.Dgfb.ТранспСр result = this.fТранспСр;
                // *** Start programmer edit section *** (ПутевойЛист.ТранспСр Get end)

                // *** End programmer edit section *** (ПутевойЛист.ТранспСр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПутевойЛист.ТранспСр Set start)

                // *** End programmer edit section *** (ПутевойЛист.ТранспСр Set start)
                this.fТранспСр = value;
                // *** Start programmer edit section *** (ПутевойЛист.ТранспСр Set end)

                // *** End programmer edit section *** (ПутевойЛист.ТранспСр Set end)
            }
        }
        
        // *** Start programmer edit section *** (ПутевойЛист.Распечатать CustomAttributes)

        // *** End programmer edit section *** (ПутевойЛист.Распечатать CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void Распечатать()
        {
            // *** Start programmer edit section *** (ПутевойЛист.Распечатать method implementation)

            return;
            // *** End programmer edit section *** (ПутевойЛист.Распечатать method implementation)
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПутевойЛистE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПутевойЛистE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПутевойЛистE", typeof(IIS.Dgfb.ПутевойЛист));
                }
            }
            
            /// <summary>
            /// "ПутевойЛистL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПутевойЛистL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПутевойЛистL", typeof(IIS.Dgfb.ПутевойЛист));
                }
            }
        }
    }
}
